all: problema1 problema2 problema3

problema1: pilha.o problema1.o
	gcc -o problema1 pilha.o problema1.o

problema2: pilha.o problema2.o
	gcc -o problema2 pilha.o problema2.o

problema3: pilha.o problema3.o
	gcc -o problema3 pilha.o problema3.o

pilha.o: pilha.c pilha.h
	gcc -c pilha.c -Wall -Werror -Wextra

problema1.o: problema1.c pilha.h
	gcc -c problema1.c -Wall -Werror -Wextra

problema2.o: problema2.c pilha.h
	gcc -c problema2.c -Wall -Werror -Wextra

problema3.o: problema3.c pilha.h
	gcc -c problema3.c -Wall -Werror -Wextra

clean:
	rm -rf *.o problema1 problema2 problema3