all: teste1 teste2 teste3

teste1: pilha.o problema1.o
	gcc -o teste1 pilha.o problema1.o

teste2: pilha.o problema2.o
	gcc -o teste2 pilha.o problema2.o

teste3: pilha.o problema3.o
	gcc -o teste3 pilha.o problema3.o

pilha.o: pilha.c pilha.h
	gcc -c pilha.c -Wall -Werror -Wextra

problema1.o: problema1.c pilha.h
	gcc -c problema1.c -Wall -Werror -Wextra

problema2.o: problema2.c pilha.h
	gcc -c problema2.c -Wall -Werror -Wextra

problema3.o: problema3.c pilha.h
	gcc -c problema3.c -Wall -Werror -Wextra

clean:
	rm -rf *.o teste1 teste2 teste3